[sshlockout.status]
command:/usr/local/opnsense/scripts/OPNsense/OpnSentralAgent/sshlockout.php
parameters:status
type:script_output
message:read SSH/WebGUI lockout trusted hosts
allowed_groups:wheel,wwwonly

[sshlockout.trust]
command:/usr/local/opnsense/scripts/OPNsense/OpnSentralAgent/sshlockout.php
parameters:trust %s
type:script_output
message:add trusted SSH/WebGUI host %s
allowed_groups:wheel,wwwonly

[sshlockout.untrust]
command:/usr/local/opnsense/scripts/OPNsense/OpnSentralAgent/sshlockout.php
parameters:untrust %s
type:script_output
message:remove trusted SSH/WebGUI host %s
allowed_groups:wheel,wwwonly

[sshlockout.sync]
command:/usr/local/opnsense/scripts/OPNsense/OpnSentralAgent/sshlockout.php
parameters:sync
type:script_output
message:synchronize trusted SSH/WebGUI hosts
allowed_groups:wheel,wwwonly
