PLUGIN_NAME=        opncentral-agent
PLUGIN_VERSION=     0.1.0
PLUGIN_COMMENT=     Minimal read-only reporting agent for opnCentral
PLUGIN_MAINTAINER=  frazon11
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
